// Generated by gencpp from file move_pkg/NaviCoord.msg
// DO NOT EDIT!


#ifndef MOVE_PKG_MESSAGE_NAVICOORD_H
#define MOVE_PKG_MESSAGE_NAVICOORD_H

#include <ros/service_traits.h>


#include <move_pkg/NaviCoordRequest.h>
#include <move_pkg/NaviCoordResponse.h>


namespace move_pkg
{

struct NaviCoord
{

typedef NaviCoordRequest Request;
typedef NaviCoordResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NaviCoord
} // namespace move_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_pkg::NaviCoord > {
  static const char* value()
  {
    return "c19bb617d86363fd7d4da46342cc0d3b";
  }

  static const char* value(const ::move_pkg::NaviCoord&) { return value(); }
};

template<>
struct DataType< ::move_pkg::NaviCoord > {
  static const char* value()
  {
    return "move_pkg/NaviCoord";
  }

  static const char* value(const ::move_pkg::NaviCoord&) { return value(); }
};


// service_traits::MD5Sum< ::move_pkg::NaviCoordRequest> should match
// service_traits::MD5Sum< ::move_pkg::NaviCoord >
template<>
struct MD5Sum< ::move_pkg::NaviCoordRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_pkg::NaviCoord >::value();
  }
  static const char* value(const ::move_pkg::NaviCoordRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_pkg::NaviCoordRequest> should match
// service_traits::DataType< ::move_pkg::NaviCoord >
template<>
struct DataType< ::move_pkg::NaviCoordRequest>
{
  static const char* value()
  {
    return DataType< ::move_pkg::NaviCoord >::value();
  }
  static const char* value(const ::move_pkg::NaviCoordRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_pkg::NaviCoordResponse> should match
// service_traits::MD5Sum< ::move_pkg::NaviCoord >
template<>
struct MD5Sum< ::move_pkg::NaviCoordResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_pkg::NaviCoord >::value();
  }
  static const char* value(const ::move_pkg::NaviCoordResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_pkg::NaviCoordResponse> should match
// service_traits::DataType< ::move_pkg::NaviCoord >
template<>
struct DataType< ::move_pkg::NaviCoordResponse>
{
  static const char* value()
  {
    return DataType< ::move_pkg::NaviCoord >::value();
  }
  static const char* value(const ::move_pkg::NaviCoordResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_PKG_MESSAGE_NAVICOORD_H
