// Generated by gencpp from file move_pkg/NaviLocationRequest.msg
// DO NOT EDIT!


#ifndef MOVE_PKG_MESSAGE_NAVILOCATIONREQUEST_H
#define MOVE_PKG_MESSAGE_NAVILOCATIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_pkg
{
template <class ContainerAllocator>
struct NaviLocationRequest_
{
  typedef NaviLocationRequest_<ContainerAllocator> Type;

  NaviLocationRequest_()
    : location_name()  {
    }
  NaviLocationRequest_(const ContainerAllocator& _alloc)
    : location_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _location_name_type;
  _location_name_type location_name;





  typedef boost::shared_ptr< ::move_pkg::NaviLocationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_pkg::NaviLocationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NaviLocationRequest_

typedef ::move_pkg::NaviLocationRequest_<std::allocator<void> > NaviLocationRequest;

typedef boost::shared_ptr< ::move_pkg::NaviLocationRequest > NaviLocationRequestPtr;
typedef boost::shared_ptr< ::move_pkg::NaviLocationRequest const> NaviLocationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_pkg::NaviLocationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_pkg::NaviLocationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move_pkg::NaviLocationRequest_<ContainerAllocator1> & lhs, const ::move_pkg::NaviLocationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.location_name == rhs.location_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move_pkg::NaviLocationRequest_<ContainerAllocator1> & lhs, const ::move_pkg::NaviLocationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::move_pkg::NaviLocationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_pkg::NaviLocationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_pkg::NaviLocationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_pkg::NaviLocationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_pkg::NaviLocationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_pkg::NaviLocationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_pkg::NaviLocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73faf335e0992a31df2e9630ffb73b0b";
  }

  static const char* value(const ::move_pkg::NaviLocationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73faf335e0992a31ULL;
  static const uint64_t static_value2 = 0xdf2e9630ffb73b0bULL;
};

template<class ContainerAllocator>
struct DataType< ::move_pkg::NaviLocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_pkg/NaviLocationRequest";
  }

  static const char* value(const ::move_pkg::NaviLocationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_pkg::NaviLocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string location_name\n"
;
  }

  static const char* value(const ::move_pkg::NaviLocationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_pkg::NaviLocationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.location_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NaviLocationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_pkg::NaviLocationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_pkg::NaviLocationRequest_<ContainerAllocator>& v)
  {
    s << indent << "location_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.location_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_PKG_MESSAGE_NAVILOCATIONREQUEST_H
