// Generated by gencpp from file move_pkg/NaviLocation.msg
// DO NOT EDIT!


#ifndef MOVE_PKG_MESSAGE_NAVILOCATION_H
#define MOVE_PKG_MESSAGE_NAVILOCATION_H

#include <ros/service_traits.h>


#include <move_pkg/NaviLocationRequest.h>
#include <move_pkg/NaviLocationResponse.h>


namespace move_pkg
{

struct NaviLocation
{

typedef NaviLocationRequest Request;
typedef NaviLocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct NaviLocation
} // namespace move_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_pkg::NaviLocation > {
  static const char* value()
  {
    return "bfc4f7f59a15d34fcc697e576374d757";
  }

  static const char* value(const ::move_pkg::NaviLocation&) { return value(); }
};

template<>
struct DataType< ::move_pkg::NaviLocation > {
  static const char* value()
  {
    return "move_pkg/NaviLocation";
  }

  static const char* value(const ::move_pkg::NaviLocation&) { return value(); }
};


// service_traits::MD5Sum< ::move_pkg::NaviLocationRequest> should match
// service_traits::MD5Sum< ::move_pkg::NaviLocation >
template<>
struct MD5Sum< ::move_pkg::NaviLocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_pkg::NaviLocation >::value();
  }
  static const char* value(const ::move_pkg::NaviLocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_pkg::NaviLocationRequest> should match
// service_traits::DataType< ::move_pkg::NaviLocation >
template<>
struct DataType< ::move_pkg::NaviLocationRequest>
{
  static const char* value()
  {
    return DataType< ::move_pkg::NaviLocation >::value();
  }
  static const char* value(const ::move_pkg::NaviLocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_pkg::NaviLocationResponse> should match
// service_traits::MD5Sum< ::move_pkg::NaviLocation >
template<>
struct MD5Sum< ::move_pkg::NaviLocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_pkg::NaviLocation >::value();
  }
  static const char* value(const ::move_pkg::NaviLocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_pkg::NaviLocationResponse> should match
// service_traits::DataType< ::move_pkg::NaviLocation >
template<>
struct DataType< ::move_pkg::NaviLocationResponse>
{
  static const char* value()
  {
    return DataType< ::move_pkg::NaviLocation >::value();
  }
  static const char* value(const ::move_pkg::NaviLocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_PKG_MESSAGE_NAVILOCATION_H
