// Generated by gencpp from file move_pkg/SetLocationResponse.msg
// DO NOT EDIT!


#ifndef MOVE_PKG_MESSAGE_SETLOCATIONRESPONSE_H
#define MOVE_PKG_MESSAGE_SETLOCATIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_pkg
{
template <class ContainerAllocator>
struct SetLocationResponse_
{
  typedef SetLocationResponse_<ContainerAllocator> Type;

  SetLocationResponse_()
    : result(false)  {
    }
  SetLocationResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::move_pkg::SetLocationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_pkg::SetLocationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetLocationResponse_

typedef ::move_pkg::SetLocationResponse_<std::allocator<void> > SetLocationResponse;

typedef boost::shared_ptr< ::move_pkg::SetLocationResponse > SetLocationResponsePtr;
typedef boost::shared_ptr< ::move_pkg::SetLocationResponse const> SetLocationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_pkg::SetLocationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_pkg::SetLocationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move_pkg::SetLocationResponse_<ContainerAllocator1> & lhs, const ::move_pkg::SetLocationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move_pkg::SetLocationResponse_<ContainerAllocator1> & lhs, const ::move_pkg::SetLocationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::move_pkg::SetLocationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_pkg::SetLocationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_pkg::SetLocationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_pkg::SetLocationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_pkg::SetLocationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_pkg::SetLocationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_pkg::SetLocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::move_pkg::SetLocationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::move_pkg::SetLocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_pkg/SetLocationResponse";
  }

  static const char* value(const ::move_pkg::SetLocationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_pkg::SetLocationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# res\n"
"bool result\n"
"\n"
;
  }

  static const char* value(const ::move_pkg::SetLocationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_pkg::SetLocationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLocationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_pkg::SetLocationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_pkg::SetLocationResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_PKG_MESSAGE_SETLOCATIONRESPONSE_H
