// Generated by gencpp from file move_pkg/SetLocationRequest.msg
// DO NOT EDIT!


#ifndef MOVE_PKG_MESSAGE_SETLOCATIONREQUEST_H
#define MOVE_PKG_MESSAGE_SETLOCATIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_pkg
{
template <class ContainerAllocator>
struct SetLocationRequest_
{
  typedef SetLocationRequest_<ContainerAllocator> Type;

  SetLocationRequest_()
    : state()
    , name()  {
    }
  SetLocationRequest_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::move_pkg::SetLocationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_pkg::SetLocationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetLocationRequest_

typedef ::move_pkg::SetLocationRequest_<std::allocator<void> > SetLocationRequest;

typedef boost::shared_ptr< ::move_pkg::SetLocationRequest > SetLocationRequestPtr;
typedef boost::shared_ptr< ::move_pkg::SetLocationRequest const> SetLocationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_pkg::SetLocationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_pkg::SetLocationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move_pkg::SetLocationRequest_<ContainerAllocator1> & lhs, const ::move_pkg::SetLocationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move_pkg::SetLocationRequest_<ContainerAllocator1> & lhs, const ::move_pkg::SetLocationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::move_pkg::SetLocationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_pkg::SetLocationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_pkg::SetLocationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_pkg::SetLocationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_pkg::SetLocationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_pkg::SetLocationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_pkg::SetLocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e80856e264f4941914a35b425212619";
  }

  static const char* value(const ::move_pkg::SetLocationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e80856e264f4941ULL;
  static const uint64_t static_value2 = 0x914a35b425212619ULL;
};

template<class ContainerAllocator>
struct DataType< ::move_pkg::SetLocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_pkg/SetLocationRequest";
  }

  static const char* value(const ::move_pkg::SetLocationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_pkg::SetLocationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# req\n"
"string state\n"
"string name\n"
;
  }

  static const char* value(const ::move_pkg::SetLocationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_pkg::SetLocationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetLocationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_pkg::SetLocationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_pkg::SetLocationRequest_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_PKG_MESSAGE_SETLOCATIONREQUEST_H
