// Generated by gencpp from file tmc_vision_msgs/DetectionArray.msg
// DO NOT EDIT!


#ifndef TMC_VISION_MSGS_MESSAGE_DETECTIONARRAY_H
#define TMC_VISION_MSGS_MESSAGE_DETECTIONARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <tmc_vision_msgs/Detection.h>

namespace tmc_vision_msgs
{
template <class ContainerAllocator>
struct DetectionArray_
{
  typedef DetectionArray_<ContainerAllocator> Type;

  DetectionArray_()
    : header()
    , detections()  {
    }
  DetectionArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::tmc_vision_msgs::Detection_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::tmc_vision_msgs::Detection_<ContainerAllocator> >> _detections_type;
  _detections_type detections;





  typedef boost::shared_ptr< ::tmc_vision_msgs::DetectionArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tmc_vision_msgs::DetectionArray_<ContainerAllocator> const> ConstPtr;

}; // struct DetectionArray_

typedef ::tmc_vision_msgs::DetectionArray_<std::allocator<void> > DetectionArray;

typedef boost::shared_ptr< ::tmc_vision_msgs::DetectionArray > DetectionArrayPtr;
typedef boost::shared_ptr< ::tmc_vision_msgs::DetectionArray const> DetectionArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tmc_vision_msgs::DetectionArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tmc_vision_msgs::DetectionArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tmc_vision_msgs::DetectionArray_<ContainerAllocator1> & lhs, const ::tmc_vision_msgs::DetectionArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.detections == rhs.detections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tmc_vision_msgs::DetectionArray_<ContainerAllocator1> & lhs, const ::tmc_vision_msgs::DetectionArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tmc_vision_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tmc_vision_msgs::DetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tmc_vision_msgs::DetectionArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tmc_vision_msgs::DetectionArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tmc_vision_msgs::DetectionArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tmc_vision_msgs::DetectionArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tmc_vision_msgs::DetectionArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tmc_vision_msgs::DetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81ce6d024652b585c906e49f2c2eb09c";
  }

  static const char* value(const ::tmc_vision_msgs::DetectionArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81ce6d024652b585ULL;
  static const uint64_t static_value2 = 0xc906e49f2c2eb09cULL;
};

template<class ContainerAllocator>
struct DataType< ::tmc_vision_msgs::DetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tmc_vision_msgs/DetectionArray";
  }

  static const char* value(const ::tmc_vision_msgs::DetectionArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tmc_vision_msgs::DetectionArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"Detection[] detections\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: tmc_vision_msgs/Detection\n"
"tmc_vision_msgs/Label label\n"
"float64 x\n"
"float64 y\n"
"float64 width\n"
"float64 height\n"
"\n"
"================================================================================\n"
"MSG: tmc_vision_msgs/Label\n"
"# label name\n"
"string name\n"
"\n"
"# confidence of this label\n"
"float64 confidence\n"
;
  }

  static const char* value(const ::tmc_vision_msgs::DetectionArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tmc_vision_msgs::DetectionArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectionArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tmc_vision_msgs::DetectionArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tmc_vision_msgs::DetectionArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::tmc_vision_msgs::Detection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // TMC_VISION_MSGS_MESSAGE_DETECTIONARRAY_H
