// Generated by gencpp from file tmc_vision_msgs/Detection.msg
// DO NOT EDIT!


#ifndef TMC_VISION_MSGS_MESSAGE_DETECTION_H
#define TMC_VISION_MSGS_MESSAGE_DETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <tmc_vision_msgs/Label.h>

namespace tmc_vision_msgs
{
template <class ContainerAllocator>
struct Detection_
{
  typedef Detection_<ContainerAllocator> Type;

  Detection_()
    : label()
    , x(0.0)
    , y(0.0)
    , width(0.0)
    , height(0.0)  {
    }
  Detection_(const ContainerAllocator& _alloc)
    : label(_alloc)
    , x(0.0)
    , y(0.0)
    , width(0.0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef  ::tmc_vision_msgs::Label_<ContainerAllocator>  _label_type;
  _label_type label;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _width_type;
  _width_type width;

   typedef double _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::tmc_vision_msgs::Detection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tmc_vision_msgs::Detection_<ContainerAllocator> const> ConstPtr;

}; // struct Detection_

typedef ::tmc_vision_msgs::Detection_<std::allocator<void> > Detection;

typedef boost::shared_ptr< ::tmc_vision_msgs::Detection > DetectionPtr;
typedef boost::shared_ptr< ::tmc_vision_msgs::Detection const> DetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tmc_vision_msgs::Detection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tmc_vision_msgs::Detection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tmc_vision_msgs::Detection_<ContainerAllocator1> & lhs, const ::tmc_vision_msgs::Detection_<ContainerAllocator2> & rhs)
{
  return lhs.label == rhs.label &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tmc_vision_msgs::Detection_<ContainerAllocator1> & lhs, const ::tmc_vision_msgs::Detection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tmc_vision_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::tmc_vision_msgs::Detection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tmc_vision_msgs::Detection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tmc_vision_msgs::Detection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tmc_vision_msgs::Detection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tmc_vision_msgs::Detection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tmc_vision_msgs::Detection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tmc_vision_msgs::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b22e438fe4366fad4149fe0a76d2b35";
  }

  static const char* value(const ::tmc_vision_msgs::Detection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b22e438fe4366faULL;
  static const uint64_t static_value2 = 0xd4149fe0a76d2b35ULL;
};

template<class ContainerAllocator>
struct DataType< ::tmc_vision_msgs::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tmc_vision_msgs/Detection";
  }

  static const char* value(const ::tmc_vision_msgs::Detection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tmc_vision_msgs::Detection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tmc_vision_msgs/Label label\n"
"float64 x\n"
"float64 y\n"
"float64 width\n"
"float64 height\n"
"\n"
"================================================================================\n"
"MSG: tmc_vision_msgs/Label\n"
"# label name\n"
"string name\n"
"\n"
"# confidence of this label\n"
"float64 confidence\n"
;
  }

  static const char* value(const ::tmc_vision_msgs::Detection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tmc_vision_msgs::Detection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Detection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tmc_vision_msgs::Detection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tmc_vision_msgs::Detection_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    s << std::endl;
    Printer< ::tmc_vision_msgs::Label_<ContainerAllocator> >::stream(s, indent + "  ", v.label);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TMC_VISION_MSGS_MESSAGE_DETECTION_H
