(cl:defpackage move_pkg-srv
  (:use )
  (:export
   "NAVICOORD"
   "<NAVICOORD-REQUEST>"
   "NAVICOORD-REQUEST"
   "<NAVICOORD-RESPONSE>"
   "NAVICOORD-RESPONSE"
   "NAVILOCATION"
   "<NAVILOCATION-REQUEST>"
   "NAVILOCATION-REQUEST"
   "<NAVILOCATION-RESPONSE>"
   "NAVILOCATION-RESPONSE"
   "SETLOCATION"
   "<SETLOCATION-REQUEST>"
   "SETLOCATION-REQUEST"
   "<SETLOCATION-RESPONSE>"
   "SETLOCATION-RESPONSE"
  ))

